/**
 * Public hosted checkout page — `/pay/[reference]`.
 *
 * Buyers access this page via a shareable link generated by the merchant.
 * The server component validates the reference, fetches the invoice from the
 * database, and renders the checkout client component with the initial data.
 *
 * No wallet session or authentication is required — this is a buyer-facing
 * page, not a merchant dashboard page.
 */
import type { Metadata } from "next";
import { notFound } from "next/navigation";

import type { Invoice } from "@/domain/entities/invoice";
import { formatMoney } from "@/domain/value-objects/money";
import { parseInvoiceReference } from "@/domain/value-objects/reference";
import { getDb } from "@/infrastructure/db/client";
import { createInvoiceRepository } from "@/infrastructure/db/invoice-repo";
import { buildPaymentUrl } from "@/lib/solana-pay-url";

import { CheckoutClient, type CheckoutInvoice } from "./_components/checkout-client";

/** Serialize the domain Invoice into the shape the client component expects. */
function toCheckoutInvoice(invoice: Invoice, appUrl: string): CheckoutInvoice {
  return {
    id: invoice.id,
    reference: invoice.reference,
    amount: {
      raw: invoice.amount.amount.toString(),
      formatted: formatMoney(invoice.amount),
      currency: invoice.amount.currency,
      decimals: invoice.amount.decimals,
    },
    label: invoice.label,
    memo: invoice.memo,
    status: invoice.status,
    expiresAt: invoice.expiresAt.toISOString(),
    createdAt: invoice.createdAt.toISOString(),
    paymentUrl: buildPaymentUrl({
      baseUrl: appUrl,
      reference: invoice.reference,
      label: invoice.label ?? undefined,
      message: invoice.memo ?? undefined,
    }),
  };
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ reference: string }>;
}): Promise<Metadata> {
  const { reference: rawRef } = await params;
  const parsed = parseInvoiceReference(rawRef);
  if (!parsed.ok) {
    return { title: "Payment · OnPay" };
  }

  const db = getDb();
  const invoiceRepo = createInvoiceRepository(db);
  const result = await invoiceRepo.findByReference(parsed.value);
  if (!result.ok || result.value === null) {
    return { title: "Payment · OnPay" };
  }

  const formatted = formatMoney(result.value.amount);
  return {
    title: `Pay ${formatted} ${result.value.amount.currency} · OnPay`,
  };
}

export default async function CheckoutPage({
  params,
}: {
  params: Promise<{ reference: string }>;
}): Promise<React.JSX.Element> {
  const { reference: rawRef } = await params;

  const parsed = parseInvoiceReference(rawRef);
  if (!parsed.ok) {
    notFound();
  }

  const db = getDb();
  const invoiceRepo = createInvoiceRepository(db);
  const result = await invoiceRepo.findByReference(parsed.value);
  if (!result.ok || result.value === null) {
    notFound();
  }

  // Read the app URL from the public env at build/render time. We import it
  // here (server component) so the client component doesn't need to access
  // process.env directly.
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  const initialInvoice = toCheckoutInvoice(result.value, appUrl);

  return <CheckoutClient initialInvoice={initialInvoice} />;
}
